/**
 * This is the CDK Class. This object is a basic data class that holds the five crucial datapoints that the CDKGlobal data will be compared to.
 * The app assumes that it is receiving a .csv file containing the full inventory generated by the CDK app. The header of the file should appear with this data:
 * |Stock No.|Stock Type|Year|Make|Model|Model No.|Model Type|Body Style|Color|Interior Color|Engine|Retail|Invoice|Lot|Co.|Age|Status|VIN|Deal No.|Mileage|
 * 
 * We are only interested in Stock No., Type, Color, Lot, and Status.
 * <ul>
 *  <li>Stock No.: The Stock Number of the vehicle. It's the primary identifier for the vehicle on the lot.</li>
 *  <li>Stock Type: Tells us if it's new or used.</li>
 *  <li>Color: Sometimes the Used Car Manager will put vital info here like "AUCTION" identifying the car as going to auction.</li>
 *  <li>Lot: This is the primary data field for Used Car Lot Status. Cars can have multpile statuses such as:
 *    <ul>
 *      <li>LOT: On the lot</li>
 *      <li>SERVICE: This car is being serviced in the back.</li>
 *      <li>SOLD: The vehicle is sold.</li>
 *      <li>WHSLE: The vehicle is being wholesaled</li>
 *      <li>ABS or MANHEIM: These are names of auto auctions that the dealership uses. Cars marked with this are at auction.</li>
 *    </ul>
 *  </li>
 *  <li>Status: This is the primary data field for New Car Lot Status. A car can be either "S" for "In Stock" or "T" for "In Transit"</li>
 * </ul>
 * 
 */
public class CDK {
	String stock;
	String type;
	String color;
	String lot;
	String status;
	
	/**
	 * Basic Constructor. Grabs the Five vital datapoints from the CDK string.
	 */
	CDK(String[] cdkItem) {
		this.stock = cdkItem[0];
		this.type = cdkItem[1];
		this.color = cdkItem[8];
		this.lot = cdkItem[13];
		this.status = cdkItem[16];
	}
	
	String getStock(){
		return this.stock;
	}
	
	String getType(){
		return this.type;
	}
	
	String getColor(){
		return this.color;
	}
	
	String getLot(){
		return this.lot;
	}
	
	String getStatus(){
		return this.status;
	}
}
